[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "openddil-ltamds-simulator"
version = "0.1.0"
description = "LTAMDS Sensor Simulator"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.100.0",
    "uvicorn>=0.23.0",
    "confluent-kafka>=2.0.0"
]